user_email_maxlen: 255
user_password_minlen: 6
user_name_maxlen: 50
true_value: "1"
gravatar_follow_size: 30
gravatar_size: 50
gravatar_default_size: 80
default_email: "noreply@example.com"
expired_time: 2
micropost_content_maxlen: 140
limit_size_image: 5
byte_to_megabyte: 1048576
accepted_image_format: "image/jpeg,image/gif,image/png"
